name: eggball
description: "Lotto Generate Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get_it: ^7.6.8
  event_bus_plus: ^0.6.2

  image_picker: ^1.1.1
  camera: ^0.11.0

  google_mlkit_text_recognition: ^0.13.0
#  google_mlkit_barcode_scanning: ^0.12.0
#  google_mlkit_digital_ink_recognition: ^0.12.0

  # Native Splash Gen
  flutter_native_splash: ^2.4.0

  # flutter_leaf_kit
  flutter_leaf_kit:
    git:
      url: https://github.com/JosephNK/flutter_leaf_kit.git
      ref: 'v1.9.20-dev'
      path: ./packages/leaf

  # Project Packages
  eb_commons: 0.0.1
  eb_components: 0.0.1
  eb_resource: 0.0.1

  # Build Gen Plugin
  dart_object_extension: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Build Gen Plugin
  build_runner: ^2.4.9
  dart_object_extension_gen: ^0.1.1

  # AppIcon Gen
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
